alias zconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias zsrc="source ~/.zshrc"
# Safely delete anything
# alias rm="trash"

alias rc="bin/rails c"
alias rs="bin/rails s"

alias cat="bat"
alias ccat="/bin/cat"

alias herkou="heroku"
alias heorku="heroku"
alias hrc="heroku run console"

alias git="hub"
alias g="git"
alias gl="git log --pretty"

alias ber="bin/rake"
alias beg="bundle exec guard"
alias mig='bin/rake db:migrate'
alias rollb='bin/rake db:rollback'

alias archive-dotfiles="cd ~/code/@dylanjha/dotfiles && yarn archive-dotfiles"

alias p="ping google.com"

# copy last git commit SHA to the clipboard
alias sha="git rev-parse HEAD | xargs echo && git rev-parse HEAD | tr -d '\n' | pbcopy && echo 'copied to clipboard'"

alias mvs="mv config/dev.secret.exs config/dev.secret.exs.hold && echo 'moved dev.secret.exs to dev.secret.exs.hold'"
alias mvb="mv config/dev.secret.exs.hold config/dev.secret.exs && echo 'moved dev.secret.exs back'"

alias ls="ls -a -1"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

bindkey '^R' history-incremental-search-backward

# Fixes slow git completion
__git_files () {
    _wanted files expl 'local files' _files
}

# HISTORY
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/Dropbox/code/shell_history
#setopt append_history no_inc_append_history no_share_history
setopt share_history

export EDITOR='Vim'
export BUNDLER_EDITOR='code'

export ANDROID_HOME=$HOME/Library/Android/sdk

export PATH=/usr/local/bin:$PATH
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:~/code/@dylanjha/code_scripts"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/Library/Android/sdk/emulator"
export PATH="$PATH:/usr/local/sbin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

autoload -U promptinit; promptinit
prompt pure

ZSH_DOTENV_FILE=.env-dylan

. ~/code/@dylanjha/dotfiles/code_scripts/key-bindings.sh
. ~/code/@dylanjha/dotfiles/code_scripts/z.sh
. ~/code/@dylanjha/dotfiles/zshell/dotenv.plugin.zsh

source ~/code/@dylanjha/dotfiles/zshell/git-completion.bash
fpath=(~/.zsh $fpath)

# fnm
eval "$(fnm env --multi)"
export GPG_TTY=$(tty)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/dylanjhaveri/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/dylanjhaveri/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/dylanjhaveri/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/dylanjhaveri/google-cloud-sdk/completion.zsh.inc'; fi

# Use python3.7 for google cloud SDK b/c 3.8 is broken
# https://github.com/GoogleCloudPlatform/gsutil/issues/961
export CLOUDSDK_PYTHON=/usr/local/opt/python@3.7/bin/python3
